apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb 
spec:
  selector:
    matchLabels:
      app: mongodb   
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo:4.4.5    
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: mongouser
            - name: MONGO_INITDB_ROOT_PASSWORD  
              value: mongopwd    
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "1028Mi"
              cpu: "400m" 

---

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: mongodb-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: mongodb
  minReplicas: 1  
  maxReplicas: 10
  targetCPUUtilizationPercentage: 80